name: Build example

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  Build_Example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Checkout Ethos-U pack repository
        uses: actions/checkout@v7
        with:
          repository: VladimirUmek/Ethos-U
          path: CMSIS-Ethos-U

      - name: Install vcpkg
        uses: ARM-software/cmsis-actions/setup-vcpkg@8a50b77681a484568e08f31fb7c2285c4735f682 # v1.3

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@8a50b77681a484568e08f31fb7c2285c4735f682 # v1.3
        with:
          config: "./vcpkg-configuration.json"
          cache:  "Tools"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@8a50b77681a484568e08f31fb7c2285c4735f682 # v1.3

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Register local pack
        run: |
          cpackget add ./CMSIS-Ethos-U/ARM.CMSIS-Ethos-U.pdsc

      - name: Cache CMSIS packs
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: cmsis-packs-${{ hashFiles('**/*.csolution.yml', '**/*.cproject.yml', '**/*.clayer.yml') }}
          restore-keys: |
            cmsis-packs-
          path: /home/runner/.cache/arm/packs

      - parallel:
        - name: Build Ethos-U55 with AC6
          run: cbuild Test-Ethos-U55.csolution.yml --packs --toolchain AC6 --output build-u55-ac6

        - name: Build Ethos-U85 with AC6
          run: cbuild Test-Ethos-U85.csolution.yml --packs --toolchain AC6 --output build-u85-ac6

        - name: Build Ethos-U55 with GCC
          run: cbuild Test-Ethos-U55.csolution.yml --packs --toolchain GCC --output build-u55-gcc

        - name: Build Ethos-U85 with GCC
          run: cbuild Test-Ethos-U85.csolution.yml --packs --toolchain GCC --output build-u85-gcc
